version: '3.8'
services:
  client:
    build: ./client
    image: vandervillain/rando:client
    depends_on:
      - server
    container_name: client
    ports:
      - '3000:3000'
  server:
    build: ./server
    image: vandervillain/rando:server
    container_name: server
    ports:
      - '5000:5000'
    env_file:
      - server/.env