name: build
on: 
  push:
    branches:
    - master
jobs:
  build:
    runs-on: windows-latest
    # strategy:
    #   matrix:
    #     node-version: [12.x, 14.x, 15.x]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '14.16.0'

      - name: Install Dependencies
        run: yarn --frozen-lockfile

      - name: Start
        run: cd server && yarn start
        run: cd client && yarn dev

      - name: Test
        uses: microsoft/playwright-github-action@v1
        run: cd client && yarn test

      - name: Publish Artifacts
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: test-artifacts
          path: artifacts