name: build
on: 
  push:
    branches:
    - master
jobs:
  build:
    runs-on: windows-latest
    # strategy:
    #   matrix:
    #     node-version: [12.x, 14.x, 15.x]
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/playwright-github-action@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '14.16.0'

      - name: Install Dependencies
        run: yarn --frozen-lockfile && yarn install-dependencies

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test

      - name: Publish Artifacts
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: Test Results
          path: client/tests/screenshots
  # deploy:
  #   runs-on: ubunto-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Install doctl
  #       uses: digitalocean/action-doctl@v2
  #       with:
  #         token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
  #     - name: Provision Droplet and deploy container
  #         run: doctl compute droplet create "$GIT_TAG_NAME" --image docker-18-04 --size s-1vcpu-1gb --region nyc1 --user-data-file deploy.sh --wait
