name: Publish
on: push
  #release:
    #types: [published]
jobs:
  test:
    name: Build and Test package
    runs-on: windows-latest
    # strategy:
    #   matrix:
    #     node-version: [12.x, 14.x, 15.x]
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/playwright-github-action@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '14.16.0'

      - name: Install Dependencies
        run: yarn --frozen-lockfile && yarn install-dependencies

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test

      - name: Publish Artifacts
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: Test Results
          path: client/tests/screenshots
  # publish:
  #   name: Push Docker image to Docker Hub
  #   runs-on: ubuntu-latest
  #   needs: [test]
  #   steps:
  #     - name: Check out the repo
  #       uses: actions/checkout@v2
  #     - name: Build containers
  #       run: docker-compose up -d.
  #     - name: Login to Docker
  #       run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
  #     - name: Push to Docker
  #       run: docker-compose push
  #     - name: Push to Docker Hub
  #       uses: docker/build-push-action@v2
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_TOKEN }}
  #         repository: vandervillain/lfp
  #         tag_with_ref: true
  deploy:
    runs-on: ubunto-latest
    steps:
      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}

          script: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
            rm lfp -rf
            git clone https://github.com/vandervillain/lfp.git
            cd lfp
            yarn docker:fresh            
            echo 'Deployment successful to digital ocean'